identifier:
  image: semtech/mu-identifier
  links:
    - dispatcher:dispatcher
  ports:
    - "80:80"
dispatcher:
  build: .
  links:
    - login:login
db:
  image: tenforce/virtuoso
  ports:
    - "8890:8890"
login:
  image: semtech/mu-login-service
  links:
    - db:database
